mod commands;
pub mod git;
pub mod pty;

use commands::{close_pty, create_pty, get_git_info, get_pty_cwd, resize_pty, write_pty};
use pty::PtyManager;
use tauri_specta::{collect_commands, Builder};

/// Create the tauri-specta builder with all commands registered.
///
/// Extracted so the same builder can be used for both the app and binding generation.
fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        create_pty,
        write_pty,
        resize_pty,
        close_pty,
        get_pty_cwd,
        get_git_info
    ])
}

/// # Panics
///
/// Panics if the Tauri application fails to initialize.
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = specta_builder();

    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::default().header(
                "// @ts-nocheck\n// This file is auto-generated by tauri-specta. Do not edit.",
            ),
            "../src/bindings.ts",
        )
        .expect("Failed to export typescript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_clipboard_manager::init())
        .manage(PtyManager::new())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[ignore = "generates src/bindings.ts — run via `just generate-bindings`"]
    fn export_typescript_bindings() {
        specta_builder()
            .export(
                specta_typescript::Typescript::default().header(
                    "// @ts-nocheck\n// This file is auto-generated by tauri-specta. Do not edit.",
                ),
                "../src/bindings.ts",
            )
            .expect("Failed to export typescript bindings");
    }
}
